### ISSUE TITLE
关于其他mcu的适配

### ISSUE THREAD

**Issue by vihor3** [MS10755/STM32_ArduinoFrame#1]
请问有没有兴趣为国产低功耗蓝牙MCU CH582M适配一下，可以的话我可以给你快递一块自己做的开发板。不是官方，纯属个人爱好者

**Comment by vihor3** [comment]
目前这款mcu官方适配了freertos和rtthread，资料完备。但是我觉得跑裸机可能更好一点

**Comment by MS10755** [comment]
> 请问有没有兴趣为国产低功耗蓝牙MCU CH582M适配一下，可以的话我可以给你快递一块自己做的开发板。不是官方，纯属个人爱好者

您好，目前还没有适配其它MCU的计划。如果您需要可以参考HC32的工程进行移植。 :-D
